# Generated by Django 3.0 on 2020-10-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='body',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='translation',
            name='date',
            field=models.DateTimeField(default=True),
        ),
    ]
