# Generated by Django 3.0.1 on 2020-11-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0002_auto_20201107_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='body',
            new_name='Input',
        ),
    ]
