# Generated by Django 3.0.1 on 2020-11-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0004_translation_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='choice',
            field=models.CharField(choices=[('Text to Binary', 'Text to Binary'), ('Binary to Text', 'Binary to Text')], default='-----------', max_length=155),
        ),
    ]
