# Generated by Django 3.0.1 on 2020-11-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0005_auto_20201107_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='Output',
            field=models.TextField(default=''),
        ),
    ]
