# Generated by Django 3.0.1 on 2020-11-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0006_translation_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='Output',
        ),
    ]
