# Generated by Django 3.0.1 on 2020-11-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0007_remove_translation_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='Output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
